//! Names that Power Automate hardcodes -- action types, runAfter statuses,
//! and the function library. Centralized so the rest of the codebase reads
//! the strings from one place instead of inlining them. If PA ever changes
//! its conventions, this is the file to edit.

/// Run-after status strings as PA writes them in the JSON. These are the
/// canonical PascalCase forms used for both `runAfter` arrays on actions
/// and the `runStatus` field on Terminate.
pub mod status {
    pub const SUCCEEDED: &str = "Succeeded";
    pub const FAILED: &str = "Failed";
    pub const SKIPPED: &str = "Skipped";
    pub const TIMED_OUT: &str = "TimedOut";
    pub const CANCELLED: &str = "Cancelled";
}

/// PA action type strings as they appear in the `type` field of each
/// action's JSON object. Also used as default action-key prefixes when
/// the user doesn't supply a name (e.g., `Compose_x`, `Apply_to_each`).
pub mod action {
    // Variable lifecycle.
    pub const INITIALIZE_VARIABLE: &str = "InitializeVariable";
    pub const SET_VARIABLE: &str = "SetVariable";
    pub const INCREMENT_VARIABLE: &str = "IncrementVariable";
    pub const DECREMENT_VARIABLE: &str = "DecrementVariable";
    pub const APPEND_TO_STRING_VARIABLE: &str = "AppendToStringVariable";
    pub const APPEND_TO_ARRAY_VARIABLE: &str = "AppendToArrayVariable";

    // Compute / data.
    pub const COMPOSE: &str = "Compose";

    // Control flow. Note: the action TYPE is `Foreach`, while the default
    // action KEY is `Apply_to_each` (see `key_prefix::APPLY_TO_EACH`).
    pub const IF: &str = "If";
    pub const SWITCH: &str = "Switch";
    pub const SCOPE: &str = "Scope";
    pub const FOREACH: &str = "Foreach";
    pub const UNTIL: &str = "Until";
    pub const TERMINATE: &str = "Terminate";

    // Default action keys generated by paxc when no user name is supplied.
    // These match the keys PA's own designer would assign.
    pub const DEFAULT_KEY_CONDITION: &str = "Condition";
}

/// Default action-key prefixes paxc generates when assigning unique action
/// names. For variable mutations, PA's own designer drops the "Variable"
/// suffix when forming the key (e.g., `InitializeVariable` action type
/// produces an `Initialize_<name>` key); these constants match that
/// convention. For control-flow actions where there's no `_<name>`
/// suffix, the prefix here is also the action type and is the same as
/// the constant in [`action`].
pub mod key_prefix {
    pub const INITIALIZE: &str = "Initialize";
    pub const SET: &str = "Set";
    pub const INCREMENT: &str = "Increment";
    pub const DECREMENT: &str = "Decrement";
    pub const APPEND_TO: &str = "Append_to";
    pub const COMPOSE: &str = "Compose";
    pub const SCOPE: &str = "Scope";
    pub const APPLY_TO_EACH: &str = "Apply_to_each";
    pub const UNTIL: &str = "Until";
    pub const SWITCH: &str = "Switch";
    pub const TERMINATE: &str = "Terminate";
    pub const CONDITION: &str = "Condition";
}

/// Trigger types as written in the `type` field of each trigger. Named
/// `trigger_type` (not `trigger`) to keep the module-level identifier
/// distinct from the AST's `Trigger` enum and from common local-variable
/// names like `trigger` in emitter functions.
pub mod trigger_type {
    pub const REQUEST: &str = "Request";
    pub const RECURRENCE: &str = "Recurrence";
}

/// Whether `name` matches a function paxr implements or a common PA
/// expression function. Used by the resolver-error diagnostic to suggest
/// "did you mean to call it?" when an undefined identifier matches a
/// known PA function. Conservative list: add only names that are clearly
/// function-shaped in PA land, to avoid false hints on plain identifier
/// typos. Pax type keywords (`array`, `object`) are excluded because they
/// are not callable PA functions; `int`, `string`, and `bool` ARE real
/// PA functions, so those stay in.
pub fn is_known_function(name: &str) -> bool {
    matches!(
        name,
        // arithmetic / logic
        "add" | "sub" | "mul" | "div" | "mod"
        | "min" | "max" | "range"
        | "concat" | "equals"
        | "less" | "lessOrEquals" | "greater" | "greaterOrEquals"
        | "not" | "and" | "or"
        // text
        | "toLower" | "toUpper" | "trim" | "substring"
        | "indexOf" | "lastIndexOf" | "startsWith" | "endsWith"
        | "replace" | "split"
        // polymorphic + array
        | "length" | "empty" | "contains"
        | "first" | "last" | "skip" | "take" | "join"
        // conversion + utility
        | "string" | "int" | "bool" | "guid"
        | "coalesce" | "createArray"
        | "uriComponent" | "uriComponentToString"
        // common PA expression functions users reach for without (...)
        | "body" | "items" | "outputs" | "variables" | "parameters"
        | "triggerBody" | "triggerOutputs"
        | "utcNow" | "formatDateTime"
    )
}
